#Note these words are containing hyphen and spaces take care of that.
words = ["hangman",
    "elephant",
    "butterfly",
    "watermelon",
    "chocolate",
    "pineapple",
    "sunflower",
    "jazz music",
    "blue sky",
    "high-quality",
    "life-sized",
    "off-the-grid",
    "old-fashioned",
    "sun-kissed",
    "time-saving",
    "user-friendly",
    "water-resistant",
    "x-ray",
    "year-round",
    "zigzag",
    "hot chocolate",
    "ice cream",
    "birthday cake",
    "rock-n-roll",
    "time travel",
    "roller coaster",
    "sand castle",
    "cherry-blossom",
    "summer vacation",
    "moonlight",
    "mountain view",
    "wildlife park",
    "hiking trail",
    "rainbow trout",
    "whispering wind",
    "swimming pool",
    "waterfall",
    "kite flying",
    "apple pie",
    "candlelight",
    "fireworks",
    "firefly",
    "merry-go-round",
    "newspaper",
    "popcorn",
    "rain shower",
    "school bus",
    "soap bubble",
    "spider web",
    "starfish",
    "teddy bear",
    "toothbrush",
    "water slide",
    "beach vacation",
    "campfire",
    "coffee shop",
    "daisy chain",
    "fairy tale",
    "garden gnome",
    "honeydew",
    "island paradise",
    "jump rope",
    "kiwi fruit",
    "ladybug",
    "mangolia",
    "nightingale",
    "ocean breeze",
    "peanut butter",
    "quilted blanket",
    "rainforest",
    "strawberry",
    "tiger cub",
    "umbrella",
    "violet flower",
    "water lily",
    "xylophone",
    "yoga mat",
    "zebra crossing"]